using SchemaFlex.Core;
using SchemaFlex.Core.Database;
using SchemaFlex.Core.Models;

namespace SchemaFlex.Tests.Unit;

public class SchemaDataHtmlReaderTests
{
    private const string Template = "<html><body><script>\nconst schemaData = __SCHEMA_JSON__;\n</script></body></html>";

    private static SchemaData SampleSchema() => new(
        "public",
        new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero),
        new List<Table>
        {
            new(
                "users",
                new List<Column>
                {
                    new("id", "integer", false, true, false, null, true, null, null),
                    new("email", "character varying(255)", false, false, true, null, false, null, null),
                },
                new List<ForeignKey>(),
                new List<CheckConstraint>(),
                new List<IndexInfo>(),
                new List<TriggerInfo>(),
                null),
        },
        new List<EnumType> { new("mood", new List<string> { "happy", "sad" }) },
        DatabaseProvider.PostgreSql);

    [Fact]
    public void Extract_round_trips_what_ErdHtmlGenerator_embedded()
    {
        var original = SampleSchema();
        var html = ErdHtmlGenerator.Generate(original, Template);

        var extracted = SchemaDataHtmlReader.Extract(html);

        Assert.Equal(original.Schema, extracted.Schema);
        Assert.Equal(original.Provider, extracted.Provider);
        Assert.Equal(original.Tables.Count, extracted.Tables.Count);
        Assert.Equal(original.Tables[0].Name, extracted.Tables[0].Name);
        Assert.Equal(original.Tables[0].Columns.Count, extracted.Tables[0].Columns.Count);
        Assert.Equal(original.Tables[0].Columns[1].DataType, extracted.Tables[0].Columns[1].DataType);
        Assert.Equal(original.Enums[0].Name, extracted.Enums[0].Name);
        Assert.Equal(original.Enums[0].Values, extracted.Enums[0].Values);
    }

    [Fact]
    public void Extract_round_trips_a_table_or_column_whose_name_contains_closing_script_tag_text()
    {
        var schemaData = new SchemaData(
            "public",
            DateTimeOffset.UtcNow,
            new List<Table>
            {
                new(
                    "users",
                    new List<Column>
                    {
                        new("bio", "text", true, false, false, null, false, null, "</script><script>alert(1)</script>"),
                    },
                    new List<ForeignKey>(),
                    new List<CheckConstraint>(),
                    new List<IndexInfo>(),
                    new List<TriggerInfo>(),
                    null),
            },
            new List<EnumType>(),
            DatabaseProvider.PostgreSql);

        var html = ErdHtmlGenerator.Generate(schemaData, Template);

        var extracted = SchemaDataHtmlReader.Extract(html);

        Assert.Equal("</script><script>alert(1)</script>", extracted.Tables[0].Columns[0].Comment);
    }

    [Fact]
    public void Extract_throws_a_clear_error_for_a_file_that_is_not_a_SchemaFlex_export()
    {
        var ex = Assert.Throws<FormatException>(() => SchemaDataHtmlReader.Extract("<html><body>not an erd file</body></html>"));
        Assert.Contains("doesn't look like an erd.html generated by SchemaFlex", ex.Message);
    }

    [Fact]
    public async Task ExtractFromFileAsync_reads_and_parses_a_real_file()
    {
        var original = SampleSchema();
        var html = ErdHtmlGenerator.Generate(original, Template);
        var path = Path.GetTempFileName();
        try
        {
            await File.WriteAllTextAsync(path, html, TestContext.Current.CancellationToken);

            var extracted = await SchemaDataHtmlReader.ExtractFromFileAsync(path, TestContext.Current.CancellationToken);

            Assert.Equal(original.Tables[0].Name, extracted.Tables[0].Name);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public async Task ExtractFromFileAsync_prefixes_the_error_with_the_file_path()
    {
        var path = Path.GetTempFileName();
        try
        {
            await File.WriteAllTextAsync(path, "not an erd file", TestContext.Current.CancellationToken);

            var ex = await Assert.ThrowsAsync<FormatException>(() => SchemaDataHtmlReader.ExtractFromFileAsync(path, TestContext.Current.CancellationToken));

            Assert.StartsWith(path, ex.Message);
        }
        finally
        {
            File.Delete(path);
        }
    }
}
