using System.Text.Json;
using SchemaFlex.Core.Models;

namespace SchemaFlex.Core;

/// <summary>
/// Reads the schema back out of an erd.html file that SchemaFlex generated earlier - what
/// lets "diff" compare against a snapshot committed to a repo or wiki instead of needing a
/// live database connection for both sides.
/// </summary>
public static class SchemaDataHtmlReader
{
    // The exact shape ErdHtmlGenerator writes: "const schemaData = <json>;" as one line,
    // immediately followed by its closing </script> tag on the next line. A plain string
    // search for that closing tag - rather than scanning for the next matching "}" - is
    // what makes this safe against a "}" appearing inside a comment or default value
    // captured in the JSON itself; the JSON payload is also guaranteed not to contain a
    // literal "</script>" sequence, since the generator escapes "</" for exactly this reason.
    private const string Marker = "const schemaData = ";
    private const string EndMarker = "\n</script>";

    public static SchemaData Extract(string html)
    {
        var start = html.IndexOf(Marker, StringComparison.Ordinal);
        if (start < 0)
        {
            throw new FormatException(
                "Could not find an embedded schema in this file - it doesn't look like an erd.html generated by SchemaFlex.");
        }

        start += Marker.Length;
        var end = html.IndexOf(EndMarker, start, StringComparison.Ordinal);
        if (end < 0)
        {
            throw new FormatException(
                "Could not find the end of the embedded schema in this file - it doesn't look like an erd.html generated by SchemaFlex.");
        }

        var jsonText = html[start..end].Trim();
        if (jsonText.EndsWith(';'))
        {
            jsonText = jsonText[..^1];
        }

        SchemaData? schemaData;
        try
        {
            schemaData = JsonSerializer.Deserialize<SchemaData>(jsonText, SchemaJson.Options);
        }
        catch (JsonException ex)
        {
            throw new FormatException("The embedded schema in this file is malformed.", ex);
        }

        return schemaData ?? throw new FormatException("The embedded schema in this file is empty.");
    }

    public static async Task<SchemaData> ExtractFromFileAsync(string path, CancellationToken token)
    {
        var html = await File.ReadAllTextAsync(path, token);
        try
        {
            return Extract(html);
        }
        catch (FormatException ex)
        {
            throw new FormatException($"{path}: {ex.Message}", ex);
        }
    }
}
