<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <!-- Embed the template files directly into the compiled binary -->
  <ItemGroup>
    <EmbeddedResource Include="templates\erd.html" />
    <EmbeddedResource Include="templates\erd-diff.html" />
  </ItemGroup>

</Project>
